#######################################################################
#                                                                     #
#              The Compcert verified compiler                         #
#                                                                     #
#          Xavier Leroy, INRIA Paris-Rocquencourt                     #
#                                                                     #
#  Copyright Institut National de Recherche en Informatique et en     #
#  Automatique.  All rights reserved.  This file is distributed       #
#  under the terms of the GNU Lesser General Public License as        #
#  published by the Free Software Foundation, either version 2.1 of   #
#  the License, or (at your option) any later version.                #
#  This file is also distributed under the terms of the               #
#  INRIA Non-Commercial License Agreement.                            #
#                                                                     #
#######################################################################

# Second-stage Makefile, after Coq extraction

include Makefile.config

#
# Variables from Makefile.config:
# -OCAML_NATIVE_COMP: native-code compilation is supported
# -OCAML_OPT_COMP: can we use the natively-compiled compilers
# -COMPFLAGS: compile options
# -LINK_OPT: additional linker flags for the native binary
#

# Menhir configuration.

include Makefile.menhir

#
# Variables from Makefile.menhir:
# -MENHIR_INCLUDES: additional menhir include paths
# -MENHIR_LIBS: additional menhir libraries
#

# The pre-parser's error message database is compiled as follows.

# cparser/pre_parser_messages.ml:
#	$(MAKE) -C cparser correct

# Directories containing plain Caml code

DIRS=extraction \
  lib common $(ARCH) cfrontend cparser driver syntax $(shell find VPL/ocaml/src -type d ! -name extracted ! -name smt)

INCLUDES=$(patsubst %,-I %, $(DIRS))

# Control of warnings:
# See: https://v2.ocaml.org/manual/toplevel.html
WARNINGS=-w +a-4-8-9-26-27-29-32-33-34-37-39-40-42-44-50-66-69-70
extraction/%.cmx: WARNINGS +=-w -20-27-32..34-39-41-44..45-60-67
extraction/%.cmo: WARNINGS +=-w -20-27-32..34-39-41-44..45-60-67

# Turn warnings into errors, but not for released tarballs
ifeq ($(wildcard .git),.git)
# WARN_ERRORS=-warn-error +a
else
WARN_ERRORS=
endif

COMPFLAGS+=-g -strict-sequence -safe-string -package zarith \
  $(INCLUDES) -I "$(MENHIR_DIR)" -I +str -I +unix -I +zarith \
  $(WARNINGS) $(WARN_ERRORS)

# Using .opt compilers if available

ifeq ($(OCAML_OPT_COMP),true)
DOTOPT=.opt
else
DOTOPT=
endif

OCAMLC=ocamlfind ocamlc $(COMPFLAGS)
OCAMLOPT=ocamlfind ocamlopt $(COMPFLAGS)
OCAMLDEP=ocamldep$(DOTOPT) -slash $(INCLUDES)

OCAMLLEX=ocamllex -q
MODORDER=tools/modorder .depend.extr
COPY=cp

PARSERS=lib/OpenScopParser.mly VPL/ocaml/src/lin/poly/PolyParser.mly
LEXERS=lib/Tokenize.mll \
	     lib/Readconfig.mll lib/Responsefile.mll lib/OpenScopLexer.mll VPL/ocaml/src/lin/poly/PolyLexer.mll \

LIBS=str.cmxa unix.cmxa zarith.cmxa $(MENHIR_LIBS)
LIBS_BYTE=$(patsubst %.cmxa,%.cma,$(patsubst %.cmx,%.cmo,$(LIBS)))

EXECUTABLES=polcert polcert.byte polopt polopt.byte cchecklink cchecklink.byte clightgen clightgen.byte
GENERATED=$(PARSERS:.mly=.mli) $(PARSERS:.mly=.ml) $(LEXERS:.mll=.ml)

.PHONY: test-extracted-zero-fallback test-typed-c-pipeline

# Beginning of part that assumes .depend.extr already exists

ifeq ($(wildcard .depend.extr),.depend.extr)

CCOMP_OBJS:=$(shell $(MODORDER) \
  extraction/TilingBandScheduleValidator.cmx \
  extraction/TilingBandMixedSecondValidator.cmx \
  extraction/TilingBandPhaseScalarValidator.cmx \
  extraction/TilingBandDirectRuntime.cmx \
  extraction/TPolOpt.cmx \
  syntax/PlutoTilingValidator.cmx \
  driver/Entry.cmx)
POLOPT_OBJS:=$(shell $(MODORDER) \
  extraction/TPolIRs.cmx \
  extraction/TPolValidator.cmx \
  extraction/TPolOpt.cmx \
  extraction/ParallelLoop.cmx \
  extraction/ParallelCodegen.cmx \
  extraction/STilingBandSched.cmx \
  extraction/SBandTilingOpt.cmx \
  extraction/SParallelPolOpt.cmx \
  extraction/SVerifiedParallelCompilerConfig.cmx \
  syntax/PlutoTilingValidator.cmx \
  syntax/SLoopMain.cmx)
EXTRACTED_ZERO_FALLBACK_OBJS:=$(shell $(MODORDER) \
  extraction/SBandTilingOpt.cmx \
  extraction/SParallelPolOpt.cmx \
  syntax/TilingValidationRoute.cmx)
EXTRACTED_ZERO_FALLBACK_TEST=tests/extracted-zero-fallback/test.cmx
TYPED_C_PIPELINE_OBJS:=$(shell $(MODORDER) \
  extraction/CTypedLoopSamples.cmx \
  extraction/PolOptBandTiling.cmx \
  extraction/ParallelPolOpt.cmx \
  driver/Scheduler.cmx)
TYPED_C_PIPELINE_TEST=tests/typed-c-pipeline/test.cmx

$(TYPED_C_PIPELINE_TEST): COMPFLAGS += -I tests/typed-c-pipeline

ifeq ($(OCAML_NATIVE_COMP),true)
polcert: $(CCOMP_OBJS)
	@echo "Linking $@"
	@$(OCAMLOPT) -o $@ $(LIBS) $(LINK_OPT) $+
else
polcert: polcert.byte
	@echo "Copying to $@"
	@$(COPY) $+ $@
endif

polcert.byte: $(CCOMP_OBJS:.cmx=.cmo)
	@echo "Linking $@"
	@$(OCAMLC) -o $@ $(LIBS_BYTE) $+

ifeq ($(OCAML_NATIVE_COMP),true)
polopt: $(POLOPT_OBJS)
	@echo "Linking $@"
	@$(OCAMLOPT) -o $@ $(LIBS) $(LINK_OPT) $+
else
polopt: polopt.byte
	@echo "Copying to $@"
	@$(COPY) $+ $@
endif

polopt.byte: $(POLOPT_OBJS:.cmx=.cmo)
	@echo "Linking $@"
	@$(OCAMLC) -o $@ $(LIBS_BYTE) $+

$(EXTRACTED_ZERO_FALLBACK_TEST): \
    extraction/SBandTilingOpt.cmi \
    extraction/SParallelPolOpt.cmi \
    syntax/TilingValidationRoute.cmi \
    VPL/ocaml/src/coq_ml/CertcheckerConfig.cmi

test-extracted-zero-fallback: \
    $(EXTRACTED_ZERO_FALLBACK_OBJS) \
    $(EXTRACTED_ZERO_FALLBACK_TEST)
	@echo "Linking /tmp/polcert-extracted-zero-fallback-gate"
	@$(OCAMLOPT) -o /tmp/polcert-extracted-zero-fallback-gate \
	  $(LIBS) $(LINK_OPT) $+
	@/tmp/polcert-extracted-zero-fallback-gate -conf polcert.ini

$(TYPED_C_PIPELINE_TEST): \
    tests/typed-c-pipeline/test.cmi \
    extraction/Datatypes.cmi \
    extraction/Result.cmi \
    extraction/ISSWitness.cmi \
    extraction/CPolIRs.cmi \
    extraction/CTypedLoopSamples.cmi \
    extraction/PolOptBandTiling.cmi \
    extraction/ParallelPolOpt.cmi \
    driver/PhaseISS.cmi \
    driver/Scheduler.cmi \
    lib/Camlcoq.cmi \
    VPL/ocaml/src/coq_ml/CertcheckerConfig.cmi

test-typed-c-pipeline: \
    $(TYPED_C_PIPELINE_OBJS) \
    $(TYPED_C_PIPELINE_TEST)
	@echo "Linking /tmp/polcert-typed-c-pipeline-test"
	@$(OCAMLOPT) -o /tmp/polcert-typed-c-pipeline-test \
	  $(LIBS) $(LINK_OPT) $+
	@/tmp/polcert-typed-c-pipeline-test -conf polcert.ini

CLIGHTGEN_OBJS:=$(shell $(MODORDER) export/ExportDriver.cmx)

ifeq ($(OCAML_NATIVE_COMP),true)
clightgen: $(CLIGHTGEN_OBJS)
	@echo "Linking $@"
	@$(OCAMLOPT) -o $@ $(LIBS) $(LINK_OPT) $+
else
clightgen: clightgen.byte
	@echo "Copying to $@"
	@$(COPY) $+ $@
endif

clightgen.byte: $(CLIGHTGEN_OBJS:.cmx=.cmo)
	@echo "Linking $@"
	@$(OCAMLC) -o $@ $(LIBS_BYTE) $+

include .depend.extr

driver/Entry.cmo driver/Entry.cmx: \
    extraction/TilingBandDirectRuntime.cmi \
    extraction/TPolOpt.cmi \
    extraction/TilingWitness.cmi \
    syntax/PlutoTilingValidator.cmi \
    lib/Camlcoq.cmi

driver/Scheduler.cmo driver/Scheduler.cmx: \
    extraction/TilingWitness.cmi \
    syntax/PlutoTilingValidator.cmi \
    lib/Camlcoq.cmi

syntax/SLoopRoute.cmo syntax/SLoopRoute.cmx: \
    syntax/SLoopConfig.cmi

syntax/SLoopCli.cmo syntax/SLoopCli.cmx: \
    syntax/SLoopConfig.cmi \
    syntax/SLoopRoute.cmi

syntax/SLoopMain.cmo syntax/SLoopMain.cmx: \
    extraction/ParallelLoop.cmi \
    extraction/ParallelCodegen.cmi \
    extraction/SParallelPolOpt.cmi \
    extraction/SVerifiedParallelCompilerConfig.cmi \
    extraction/Validator.cmi \
    extraction/TPolValidator.cmi \
    extraction/TPolOpt.cmi \
    extraction/SBandTilingOpt.cmi \
    extraction/TilingWitness.cmi \
    driver/Scheduler.cmi \
    syntax/SLoopCli.cmi \
    syntax/SLoopCommon.cmi \
    syntax/SLoopDispatch.cmi \
    syntax/SLoopProfile.cmi \
    syntax/SLoopIss.cmi \
    syntax/TilingValidationRoute.cmi \
    lib/Camlcoq.cmi

# These modules have no .mli file.  Compile each implementation with ocamlc
# first so there is one stable owner of its inferred interface.  Native
# compilation then consumes that .cmi instead of racing with or replacing it.
NO_MLI_MODULES := \
	lib/Camlcoq \
	syntax/TilingValidationRoute \
	extraction/ImpureConfig \
	extraction/SParallelPolOpt \
	extraction/ParallelPolOpt \
	extraction/PolOptBandTiling \
	extraction/TilingBandScheduleValidator \
	extraction/TilingBandMixedSecondValidator \
	extraction/TilingBandPhaseScalarValidator \
	extraction/TilingBandDirectRuntime \
	extraction/STilingBandSched \
	extraction/SBandTilingOptShared \
	extraction/SParallelPolOptShared \
	extraction/SBandTilingOpt \
	driver/PhaseISS \
	driver/Scheduler \
	syntax/PlutoTilingValidator \
	syntax/SLoopCli \
	syntax/SLoopCommon \
	syntax/SLoopConfig \
	syntax/SLoopDispatch \
	syntax/SLoopIss \
	syntax/SLoopProfile \
	syntax/SLoopRoute

NO_MLI_CMIS := $(addsuffix .cmi,$(NO_MLI_MODULES))
NO_MLI_CMXS := $(addsuffix .cmx,$(NO_MLI_MODULES))

$(NO_MLI_CMIS): %.cmi: %.cmo
	@true

$(NO_MLI_CMXS): %.cmx: %.cmo %.ml
	@echo "OCAMLOPT $*.ml"
	@$(OCAMLOPT) -c $*.ml

endif

# End of part that assumes .depend.extr already exists

%.cmi: %.mli
	@echo "OCAMLC   $<"
	@$(OCAMLC) -c $<
%.cmo: %.ml
	@echo "OCAMLC   $<"
	@$(OCAMLC) -c $<
%.cmx: %.ml
	@echo "OCAMLOPT $<"
	@$(OCAMLOPT) -c $<

%.ml: %.mll
	$(OCAMLLEX) $<

clean:
	rm -f $(EXECUTABLES)
	rm -f tests/typed-c-pipeline/*.cm[iotx] \
	      tests/typed-c-pipeline/*cmti \
	      tests/typed-c-pipeline/*.o
	rm -f $(GENERATED)
	for d in $(DIRS); do rm -f $$d/*.cm[iotx] $$d/*cmti $$d/*.o; done
	rm -f tests/extracted-zero-fallback/*.cm[iotx] \
	      tests/extracted-zero-fallback/*cmti \
	      tests/extracted-zero-fallback/*.o
# $(MAKE) -C cparser clean

# Generation of .depend.extr

depend: $(GENERATED)
	@echo "Analyzing OCaml dependencies"
	@$(OCAMLDEP) $(foreach d,$(DIRS),$(wildcard $(d)/*.ml)) $(GENERATED) >.depend.extr || { rm -f .depend.extr; exit 2; }
	@$(OCAMLDEP) $(foreach d,$(DIRS),$(wildcard $(d)/*.mli)) $(GENERATED) >>.depend.extr || { rm -f .depend.extr; exit 2; }
